name: runtime_lints
description: Recommended linting/analysis rules for
version: 0.1.0
homepage: https://github.com/open-runtime/runtime_lints
repository: https://github.com/open-runtime/runtime_lints

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  lints: ^1.0.1

# dev_dependencies:
# NOTE: Code is not allowed in this package. Do not add dependencies.
