name: runtime_lints
description: Recommended linting/analysis rules for OpenRuntime Github Organization
version: 0.2.0
homepage: https://github.com/open-runtime/runtime_lints
repository: https://github.com/open-runtime/runtime_lints

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter_lints: ^1.0.4

# dev_dependencies:
# NOTE: Code is not allowed in this package. Do not add dependencies.
